name: ZAP Baseline Scan

on:
  workflow_call:

jobs:
  zap-baseline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start the application
        run: docker-compose -f docker-compose.yml up -d

      - name: Wait for application to be ready
        run: |
          echo "Waiting for app to start..."
          sleep 30
          curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:8080
          curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:8081

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://localhost:8081'
          # rules_file_name: '.zap/rules.tsv'
          cmd_options: '-I'  #
          allow_issue_writing: false

      - name: Stop the application
        run: docker-compose -f docker-compose.yml down