name: ZAP Baseline Scan

on:
  workflow_call:

jobs:
  zap-baseline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start services
        run: docker compose -f docker-compose.yml up -d --build

      - name: Wait for application to be ready
        run: |
          echo "Waiting for app to start..."
          sleep 30
          curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:8080
          curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:8081

      - name: ZAP Full Scan (with authentication)
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://localhost:8081'
          cmd_options: >
            -I
            --auth-form-url="http://localhost:8081/login"
            --auth-form-user="${{ secrets.ZAP_USERNAME }}"
            --auth-form-pass="${{ secrets.ZAP_PASSWORD }}"
            --auth-form-username-field="email"
            --auth-form-password-field="password"
            allow_issue_writing: false
            artifact_name: zap_full_scan

      - name: Stop the application
        run: docker compose -f docker-compose.yml down
