name: ZAP Full Scan (Dockerized app)

on:
  workflow_call:
    secrets:
      SECRET_JWT:
        required: true
      SECRET_KEY_AES:
        required: true
      MAIL_USERNAME:
        required: true
      MAIL_PASSWORD:
        required: true
      OAUTH_GITHUB_CLIENT_ID:
        required: true
      OAUTH_GITHUB_CLIENT_SECRET:
        required: true

jobs:
  zap-full-scan:
    runs-on: ubuntu-latest
    env:
      BACKEND_URL: http://backend:8080
      FRONTEND_URL: http://frontend:80

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "SPRING_DATASOURCE_URL=jdbc:postgresql://restaurant_database:5432/reservsystem" >> .env
          echo "SPRING_DATASOURCE_USERNAME=usersystem" >> .env
          echo "SPRING_DATASOURCE_PASSWORD=passreserv" >> .env
          echo "SECRET_JWT=${{ secrets.SECRET_JWT }}" >> .env
          echo "SECRET_KEY_AES=${{ secrets.SECRET_KEY_AES }}" >> .env
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
          echo "GITHUB_CLIENT_ID=${{ secrets.OAUTH_GITHUB_CLIENT_ID }}" >> .env
          echo "GITHUB_CLIENT_SECRET=${{ secrets.OAUTH_GITHUB_CLIENT_SECRET }}" >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start services
        run: |
          docker compose -f docker-compose.yml up -d --build

      - name: Wait for backend to be ready
        run: |
          echo "Waiting for backend to start..."
          for i in {1..30}; do
            if docker compose exec backend curl -s http://localhost:8080/api/reservation/tables >/dev/null 2>&1; then
              echo "Backend is ready!"
              exit 0
            fi
            sleep 5
            echo "Waiting for backend... ($i/30)"
          done
          echo "Backend did not start properly."
          docker compose logs backend
          exit 1

      - name: Create test user for ZAP scanning
        run: |
          echo "Creating test user for ZAP scanning..."
          docker exec -i restaurant_database psql -U usersystem -d reservsystem << EOF
          INSERT INTO users (username, email, password, role, enabled)
          VALUES ('zapuser', 'zap@example.com', '\$2a\$10\$N9qo8uLOickgx2ZMRZoMye3s3e6T7eQ6Y5q6U6U6U6U6U6U6U6U6U6', 'USER', true)
          ON CONFLICT (email) DO NOTHING;
          EOF

      - name: Find Docker network name
        run: |
          # Βρίσκουμε αυτόματα το network name
          NETWORK_NAME=$(docker network ls --filter "name=app-network" --format "{{.Name}}")
          if [ -z "$NETWORK_NAME" ]; then
            NETWORK_NAME=$(docker compose ps -q backend | xargs -I {} docker inspect {} --format '{{range .NetworkSettings.Networks}}{{.NetworkID}}{{end}}' | head -1 | xargs -I {} docker network inspect {} --format '{{.Name}}')
          fi
          echo "NETWORK_NAME=$NETWORK_NAME" >> $GITHUB_ENV
          echo "Using network: $NETWORK_NAME"

      - name: Run ZAP baseline scan
        run: |
          # Δημιουργούμε το config file που απαιτείται
          cat > gen.conf << 'EOF'
          # ZAP Baseline Scan configuration
          rules:
          EOF
          
          # Χρησιμοποιούμε το zaproxy/zap-stable image με πιο απλές παραμέτρους
          docker run --rm \
            --network ${{ env.NETWORK_NAME }} \
            -v $(pwd):/zap/wrk \
            -t zaproxy/zap-stable \
            zap-baseline.py \
            -t http://backend:8080 \
            -g gen.conf \
            -I  # ΔΕΝ αποτυγχάνει σε warnings, μόνο σε critical errors

      - name: Check if ZAP reports were generated
        run: |
          if [ -f zap-report.html ]; then
            echo "✅ ZAP scan completed successfully"
            echo "Reports generated:"
            ls -la zap-report.*
          else
            echo "⚠️ ZAP reports not found - scan may have had issues"
            # Δεν αποτυγχάνουμε γιατί μπορεί να μην δημιουργήθηκε report
          fi

      - name: Upload ZAP artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-reports
          path: |
            zap-report.html
            zap-report.json
            zap-report.xml
            gen.conf
          if-no-files-found: warn

      - name: Stop services
        if: always()
        run: docker compose -f docker-compose.yml down --volumes --remove-orphans